paragraphs = [
    "Once upon a time, in a quaint little village nestled between rolling hills and crystal-clear lakes, there lived a young boy named Oliver. He was an imaginative and adventurous child, always seeking out new tales and exciting experiences. One sunny morning, as he awoke to the melodious chirping of birds, Oliver felt an inexplicable urge to embark on a grand adventure. With a determined glint in his eyes, Oliver packed a small knapsack with essential supplies: a map, a compass, a water bottle, and a few snacks. He waved goodbye to his worried parents and set off on a journey through the enchanted forest that bordered his village. As he ventured deeper into the woods, the air grew thicker with mystery. Oliver's senses heightened, and he could almost feel the magic pulsating through the trees. Guided by his unwavering curiosity, he followed the faint sound of a distant waterfall. After walking for what felt like hours, Oliver stumbled upon a hidden clearing bathed in ethereal light. There, he discovered an ancient stone archway entwined with vines and shimmering with enchantments. As he approached it, the archway began to emanate a soft, golden glow.",
    "Without hesitation, Oliver stepped through the archway and found himself in an entirely new realm—a place where dreams mingled with reality, and extraordinary beings roamed freely. The land was called Eldoria, a realm known only in folklore and whispered legends. Oliver's eyes widened in awe as he took in the breathtaking scenery. Towering trees with emerald leaves reached for the sky, and peculiar creatures darted among the branches. He had stumbled upon a world beyond his wildest dreams, a world that had chosen him as its visitor. Curiosity urged Oliver forward, and he set off to explore Eldoria. In this mystical realm, he encountered talking animals who shared ancient wisdom, kind-hearted fairies who granted wishes, and mischievous goblins who loved to play tricks. Each encounter brought him closer to unraveling the secrets of Eldoria and discovering his own destiny. One day, while traversing a treacherous mountain path, Oliver stumbled upon a wounded dragon named Ember. She had been captured by a group of dark sorcerers who sought to exploit her immense power. With compassion in his heart, Oliver vowed to rescue Ember and protect her from harm.",
    "Gathering a band of loyal friends he had made during his journey, including a brave knight named Sir Roland and a wise sorceress named Luna, Oliver set forth on a perilous quest to free Ember from her captors. Their path was riddled with challenges and dangers, but their unwavering determination carried them forward. Through the dark caverns and across the raging rivers, Oliver and his companions fought valiantly against the sorcerers' minions. They braved enchanted forests and solved intricate puzzles, using their wit and courage to overcome each obstacle in their path. Finally, after a series of arduous trials, Oliver and his friends reached the sorcerers' lair—a sprawling fortress carved into the side of a mountain. With their hearts pounding, they prepared for the final confrontation. As the doors of the fortress swung open, Oliver stood face to face with the sorcerers. Their eyes burned with malevolence, but Oliver's determination remained unshaken. With a resounding battle cry, he charged forward, leading his friends into a fierce battle against the dark forces.",
    "In a dazzling display of bravery and magic, Oliver and his companions emerged victorious. The sorcerers were vanquished, and Ember was free at last. The realm of Eldoria rejoiced, and the creatures that had befriended Oliver celebrated his triumph. Embracing his newfound role as a hero, Oliver bid farewell to Eldoria, knowing he had fulfilled his destiny in that mystical realm. With Ember by his side, he returned to his village, where his parents greeted him with a mixture of relief and pride. Oliver's grand adventure had come to an end, but his heart was forever touched by the wonders he had encountered and the friendships he had forged. He knew that no matter where life took him, the spirit of Eldoria would always reside within him—a reminder of the magic that lies within every person who dares to dream and believe in the extraordinary. And with that, Oliver embarked on the next chapter of his life, forever carrying the enchantment of Eldoria in his heart.",
    "In the heart of a bustling city named Arcadia, there lived a young girl named Lily. She possessed an insatiable thirst for knowledge and a burning passion for adventure. With her wild curls and a mischievous twinkle in her eyes, Lily was a free spirit who was always seeking new experiences. One fateful afternoon, as Lily strolled through the labyrinthine alleys of Arcadia's old quarter, she stumbled upon a weathered bookshop tucked away between two towering buildings. The sign above the door read, The Curious Attic: Where Stories Come Alive. Intrigued, Lily pushed open the creaking door and entered the mysterious shop. Inside, she discovered a treasure trove of books stacked high to the ceiling. The air was thick with the scent of ancient pages and whispered tales. As Lily explored the nooks and crannies, she noticed a peculiar staircase leading up to a small, dusty attic. Curiosity piqued, Lily climbed the staircase, her heart pounding with excitement. Upon reaching the attic, she gasped in awe. The room was filled with magical objects, each pulsating with its own unique energy. There were old maps, enchanted trinkets, and shimmering crystals that seemed to hold the secrets of the universe.",
    "In the corner of the attic stood an ornate mirror, its frame adorned with intricate carvings. As Lily approached, the mirror glimmered, drawing her closer. She stared into its depths, captivated by her own reflection, when suddenly, a voice whispered from within. Welcome, dear traveler, the voice said. I am the Mirror of Imagination. I have been waiting for someone like you. Startled yet intrigued, Lily leaned in closer. The mirror continued, I have the power to transport you to the worlds within books. With me, you can become a part of every story, experiencing adventures beyond your wildest dreams. Without hesitation, Lily reached out and touched the mirror's cool surface. In an instant, she found herself engulfed in a whirlwind of colors and sensations. When the whirlwind subsided, Lily opened her eyes and found herself standing in a lush, fantastical forest. She had entered the world of The Enchanted Chronicles, a land where mythical creatures roamed and magic danced through the air. Excitement surged through Lily's veins as she realized that she was now a character within the pages of a book.",
    "Lily embarked on extraordinary adventures, journeying through enchanted realms and meeting fascinating characters along the way. She befriended a wise elf who taught her the ancient art of elemental magic, she encountered talking animals who revealed hidden truths, and she even participated in a daring quest to save a kingdom from an evil sorcerer. With each adventure, Lily grew wiser and more confident. She discovered her own strengths and learned to overcome her fears. The realms within the book became her second home, and the characters within its pages became her dearest friends. But as all stories do, Lily's time in The Enchanted Chronicles came to an end. The mirror summoned her back to the attic, where she stood once again before the ornate frame. Grateful for the experiences and lessons she had gained, Lily bid farewell to the world within the book, knowing that its magic would forever be a part of her. As she stepped away from the mirror, Lily felt a warm glow in her heart. She realized that the magic of books was not confined to the pages; it lived within her, igniting her imagination and inspiring her to seek adventure in the world around her.",
    "Deep in the heart of the ancient forest, there stood a desolate mansion known as Blackthorn Manor. Its crumbling façade and overgrown gardens whispered tales of a tragic past. Locals warned of the darkness that lurked within its walls, recounting stories of strange occurrences and unexplained disappearances. It was a place that sent shivers down the spines of even the bravest souls. One stormy night, a group of adventurous friends—Sophie, Mark, Emily, and Alex—gathered around a flickering campfire, sharing tales of the supernatural. Emboldened by their own curiosity, they made a pact to explore the infamous Blackthorn Manor, determined to unravel its mysteries. Armed with flashlights, they approached the mansion with trepidation. The wind howled through the trees, creating an eerie symphony that matched the pounding of their hearts. As they stepped over the threshold, the air grew heavy, and an icy chill crept down their spines. Inside the mansion, shadows danced along the walls, whispering secrets long forgotten. The floorboards creaked beneath their feet, and a musty odor filled the air. Each room they entered revealed more evidence of a haunting past—a broken doll in one corner, a tattered wedding dress in another.",
    "As they ventured deeper into the manor, a feeling of unease settled upon them. Strange noises echoed through the halls, and the temperature plummeted. Doors slammed shut without warning, trapping them in dimly lit corridors. Whispers grew louder, and sinister laughter echoed in their ears. It was as if the very essence of the house was taunting them, testing their courage. Panic gripped their hearts, and the group realized they were no longer alone. Their flashlights flickered, casting eerie shadows on the decaying wallpaper. Desperate to escape the clutches of the manor, they followed a set of winding stairs that led to the attic—a place where the darkness seemed to be at its strongest. In the attic's gloom, they discovered a collection of antique items—a dusty mirror, an ancient family photo, and a worn journal. Emily reached out to touch the mirror, and her reflection flickered, revealing a ghastly figure lurking behind her. Petrified, she stumbled backward, crashing into a stack of old furniture.",
    "The group huddled together, their breath shallow, as a voice, icy and malicious, whispered from the darkness, recounting the tale of the mansion's haunting. Long ago, a powerful sorceress named Lady Eveline Blackthorn resided in the manor, practicing dark magic that consumed her soul. The sorceress's vengeful spirit remained trapped within the mansion, seeking release by luring unsuspecting souls into her clutches. Sophie, Mark, Emily, and Alex had become her latest victims, ensnared in a web of fear and despair. As the voice faded, a chilling silence settled over the attic. Suddenly, the group found themselves surrounded by ethereal figures, each wearing a sorrowful expression. They were the lost souls who had fallen victim to Lady Eveline's curse, forever trapped within the confines of Blackthorn Manor. In a desperate bid to break free from the spirit's grasp, Sophie remembered the worn journal. With trembling hands, she opened it to the last entry—a desperate plea for salvation. The group realized that they held the key to freeing both themselves and the tormented souls. Summoning their courage, they chanted an incantation, their voices resonating with a power they didn't know they possessed. The air crackled with energy as the mansion trembled, and Lady Eveline's spectral form emerged before them, her eyes filled with malice.",
    "With a final surge of determination, they recited the incantation, banishing the sorceress's spirit from the manor. In an instant, the mansion was consumed by a blinding light, and as it faded, Blackthorn Manor stood empty and lifeless once again. Sophie, Mark, Emily, and Alex emerged from the mansion, their hearts heavy but filled with relief. They had survived the horror that lurked within Blackthorn Manor, freeing both themselves and the lost souls trapped within its walls. Never again would the manor hold sway over the innocent, for the group had broken the curse and laid the tormented spirits to rest. And as they walked away from the haunted mansion, they vowed to cherish the gift of life and to forever remember the chilling tale of Blackthorn Manor, a testament to the enduring power of courage and friendship in the face of unimaginable darkness.",
    "Deep in the heart of a dense forest, there existed a forgotten village named Ravenswood. The village was shrouded in a perpetual mist, its dilapidated houses standing as a haunting reminder of a tragic event that had befallen its inhabitants Legend had it that many years ago, the village was cursed by an ancient witch who had been wronged by the villagers. The witch's vengeful spirit had cast a spell upon Ravenswood, trapping its residents in a perpetual state of fear and darkness. Word of the village's cursed existence had reached the ears of a renowned paranormal investigator named Samuel. Driven by a thirst for knowledge and a desire to uncover the truth, Samuel embarked on a perilous journey to Ravenswood, determined to unravel the mysteries that lay within. As Samuel arrived at the village's outskirts, a bone-chilling wind whispered through the trees, carrying the echoes of distant cries. He took a deep breath, his heart pounding, and stepped into the village's desolate streets. The atmosphere was heavy with an otherworldly presence, as if unseen eyes were watching Samuel's every move. The houses stood in disarray, their windows shattered and their doors hanging from rusty hinges. The silence was suffocating, broken only by the occasional hushed whispers that seemed to emanate from the shadows.",
    "Guided by an old map he had discovered, Samuel made his way to the village square. In the center stood a dilapidated well, its stone structure crumbling with age. It was said to be the source of the curse that plagued Ravenswood. As Samuel approached the well, he noticed a faint glimmer of light emanating from its depths. Intrigued, he knelt down and peered inside. To his astonishment, the well seemed to stretch endlessly, revealing a hidden passage that led to an underground chamber. Without hesitation, Samuel descended into the depths, his flashlight piercing the darkness. The air grew heavier, and an oppressive energy enveloped him. The chamber was adorned with symbols of dark magic, and the walls were etched with the history of the witch's curse In a corner of the chamber, Samuel discovered a weathered book, its pages filled with incantations and ancient knowledge. As he deciphered the cryptic text, he realized that the key to breaking the curse lay in performing a ritual of forgiveness—a way to release the witch's spirit from its eternal torment. With determination in his heart, Samuel returned to the village square and called upon the villagers, both living and trapped spirits, to gather. He shared the tale of the witch's grievance and implored the villagers to forgive her, to release the cycle of pain that had held Ravenswood captive for so long.",
    "The atmosphere crackled with tension as the villagers contemplated Samuel's words. Slowly, one by one, they stepped forward, their voices trembling with emotion as they forgave the witch for the past wrongs. Their forgiveness reverberated through the air, filling Ravenswood with a newfound hope. In a blinding burst of light, the curse was broken. The mist that had enshrouded the village lifted, revealing a once-forgotten beauty. The houses were restored to their former glory, and the villagers were freed from the clutches of fear. Samuel stood in awe as Ravenswood transformed before his eyes. The village, once haunted by tragedy, now pulsed with life and joy. The villagers, both living and spirits, came together in celebration, their faces radiant with newfound hope and peace. As Samuel bid farewell to Ravenswood, he knew that he had witnessed something extraordinary—a testament to the power of forgiveness and the strength of the human spirit. The village, once cursed and forgotten, had been granted a second chance, and the tale of Ravenswood would forever be etched in Samuel's memory, a reminder that even in the darkest of times, redemption and healing are possible.",
    "In the small coastal town of Havenbrook, there was a charming lighthouse that stood tall against the crashing waves. The lighthouse keeper, an old sailor named Captain Benjamin, had devoted his life to guiding ships safely to shore. One stormy night, a tempest unlike any other descended upon Havenbrook. The winds howled with fury, and the sea raged with monstrous waves. As the townsfolk sought shelter, they noticed with growing concern that the lighthouse's beacon had flickered and died. Captain Benjamin, determined to fulfill his duty, ventured into the heart of the storm. With the wind whipping through his gray hair, he climbed the treacherous steps of the lighthouse, his lantern illuminating the way. But when he reached the top, a sight that filled him with dread awaited him. The lighthouse lantern had shattered, its glass shards scattered across the floor. It seemed as if the very essence of the storm had invaded the once serene tower. Undeterred, Captain Benjamin knew he had to find a way to guide the ships to safety. In the dim light, he spotted a small, weathered book tucked away in a forgotten corner of the lighthouse. The book was filled with ancient maritime tales, whispered legends of a mythical gem known as the Sea's Tear—an artifact said to possess the power to calm even the fiercest storms.",
    "Driven by desperation, Captain Benjamin embarked on a perilous quest to find the Sea's Tear. Armed with the book's instructions and his unwavering determination, he set sail aboard his trusty vessel, the Seraph. The journey was treacherous, with the storm raging relentlessly. Lightning cracked across the sky, and the waves threatened to engulf the ship. But Captain Benjamin remained resolute, his eyes fixed on the horizon. Days turned into weeks, and the crew's hope wavered. Doubt crept into their hearts, but Captain Benjamin reassured them with tales of the",
    "Detective Sarah Walker stared at the crime scene before her—a lavish penthouse apartment with floor-to-ceiling windows offering a panoramic view of the city. The opulence and grandeur of the space contrasted starkly with the lifeless body lying on the marble floor. The victim, Richard Sutton, a renowned billionaire philanthropist, had been found dead in his own home, a single gunshot wound to the chest. Sarah knew this was no ordinary murder case. The stakes were high, and she had to find the truth. As she meticulously examined the crime scene, Sarah noticed something peculiar—a small, intricately crafted silver key lying near the body. It didn't belong to Sutton or his personal belongings, suggesting a possible connection to the crime. She carefully bagged it as evidence and began her investigation. Sarah delved into Sutton's life, unraveling a complex web of secrets and deceit. Interviews with friends and associates revealed that Sutton had made many enemies over the years. His vast fortune had fueled gred and envy among those close to him. One name that surfaced repeatedly was Daniel Reynolds, a former business partner who had a bitter falling out with Sutton. Rumors circulated that Reynolds had been planning revenge, but Sarah needed solid evidence to connect him to the crime.",
    "As she dug deeper, Sarah discovered that Sutton had been involved in illegal financial activities. Money laundering, embezzlement—his empire was built on a foundation of lies. It seemed that someone had taken matters into their own hands, seeking to expose Sutton's misdeeds and bring him down. Sarah pursued leads relentlessly, following a trail of hidden offshore accounts, forged documents, and illicit transactions. The more she uncovered, the closer she got to the truth. She needed a breakthrough—a piece of evidence that would crack the case wide open. Late one night, as Sarah poured over financial records, a name caught her eye—Emma Hayes, Sutton's personal assistant. She had access to his accounts and intimate knowledge of his illegal activities. Sarah's instincts told her that Emma held the key to unraveling the entire conspiracy. With a renewed sense of purpose, Sarah tracked down Emma and brought her in for questioning. The young woman appeared nervous and evasive, but under the pressure of the interrogation, she confessed to being involved in Sutton's criminal activities. Emma revealed that she had discovered a plan to embezzle millions from Sutton's accounts. Fearing the consequences of her involvement, she had conspired with Reynolds to expose Sutton's crimes and bring him down. But their plan had spiraled out of control, leading to Sutton's murder.",
    "As Sarah pieced together the puzzle, she realized that Sutton's death was not the result of a random act of violence. It was a carefully orchestrated plan to silence him, to protect the secrets that could destroy countless lives. Sarah worked tirelessly to gather the evidence needed to bring Reynolds and Emma to justice. She unraveled their intricate web of deception, connecting the dots that led to the murder of Richard Sutton. In a dramatic courtroom showdown, the truth was revealed. Reynolds, driven by vengeance and greed, had orchestrated the murder, using Emma as a pawn in his deadly game. Their plan had been to frame Sutton's death as a result of his criminal activities, effectively tarnishing his reputation beyond repair. But justice prevailed. Reynolds and Emma were found guilty of their crimes, the weight of their actions finally catching up to them. The courtroom erupted in applause as the verdict was announced. As Sarah walked away from the courtroom, she knew that justice had been served. The crime had been solved, the truth had been uncovered, and Richard Sutton's death had been avenged. But the case would forever serve as a reminder that even behind the façade of wealth and power, darkness lurked, waiting to be exposed by those who dared to seek the truth.",
    "In the heart of the bustling city, a notorious criminal known as The Night Phantom wreaked havoc, leaving a trail of perplexing heists in his wake. Detective Ethan Collins had dedicated his career to catching this elusive mastermind, and he wasn't about to let him slip through his fingers again. The Night Phantom had a unique signature—a distinctive symbol carved into the scene of every crime. The latest heist had taken place at the city's most prestigious art gallery, where a priceless diamond necklace had vanished without a trace. As Ethan examined the scene, he noticed a small card left behind, bearing the Phantom's symbol. Driven by determination, Ethan meticulously studied the clues, scouring the city for any leads. Late nights turned into early mornings as he delved deeper into the Phantom's twisted mind. He knew he needed to think like the criminal, anticipate his every move. Days turned into weeks, and with each passing heist, the Phantom's audacity grew. Banks, museums, and high-profile events—no location was safe from his calculated schemes. Ethan's frustration mounted, but he refused to let it consume him. He had to keep pushing forward, searching for that one break in the case. Then, a breakthrough—a witness who claimed to have seen a shadowy figure lurking near the art gallery on the night of the diamond heist. The witness described a man with a distinct limp—a detail that hadn't been previously reported. It was a valuable piece of information that could help identify the Phantom.",
    "Ethan meticulously compiled a profile of the criminal—a brilliant strategist with a penchant for theatrics. He studied the Phantom's previous heists, noticing a pattern—a fascination with rare gems and an obsession with puzzles. It became clear to Ethan that the key to capturing the Phantom lay in unraveling his twisted mind. Armed with this newfound insight, Ethan devised an audacious plan of his own. He would set a trap, luring the Phantom into a web of his own making. He enlisted the help of a talented cryptographer, Alexandra Hughes, to create an elaborate puzzle that would challenge even the Phantom's intellect. The trap was set—a gala event hosted by a renowned philanthropist, rumored to be in possession of a valuable gem. It was the perfect bait to entice the Phantom. As the night of the event arrived, Ethan and Alexandra waited in anticipation, hidden among the crowd. The tension mounted as the evening unfolded. The guests were enthralled by the grandeur, unaware of the imminent danger. Then, the room plunged into darkness, the power cut off. Panic ensued, and amid the chaos, the Phantom struck. In the ensuing commotion, Ethan and Alexandra sprang into action. They followed the Phantom's trail, navigating through hidden passages and intricate puzzles. Each step brought them closer to the elusive criminal, their hearts pounding with adrenaline.",
    "Finally, they cornered him in a secret room, the walls adorned with stolen treasures. The Phantom, a man named Raymond Morgan, smirked as he realized he had been outsmarted. But Ethan was ready—he had anticipated every move. A tense standoff ensued as Ethan and Raymond locked eyes. It was a battle of wits and wills, a showdown between the hunter and the hunted. In the end, it was Ethan's unwavering resolve and the pursuit of justice that emerged victorious. Raymond Morgan, aka the Night Phantom, was apprehended, his reign of terror finally put to an end. The city breathed a collective sigh of relief, and Ethan received accolades for his tenacity and brilliance. As he reflected on the case, Ethan knew that the chase had changed him. It had tested his limits and pushed him to the brink. But it had also reinforced his belief in the power of justice and the resilience of the human spirit. And so, Detective Ethan Collins continued his fight against crime, knowing that there would always be those who sought to test the boundaries of law and order. But armed with his unwavering determination, he remained vigilant, ready to face any challenge that came his way.",
    "In the heart of a vibrant metropolis, a string of inexplicable disappearances sent shockwaves through the community. People vanished without a trace, leaving behind only a haunting sense of mystery. The city was gripped with fear, and it fell upon Detective Olivia Sullivan to unravel the enigma behind these perplexing cases. Olivia was a seasoned investigator known for her sharp instincts and unwavering dedication. As she delved into the disappearances, she noticed a pattern—a series of strange symbols that appeared at each crime scene. They seemed cryptic, hinting at a hidden message yet to be deciphered. Driven by a relentless pursuit of the truth, Olivia reached out to an eccentric linguistics professor named Dr. Sebastian Wolfe, known for his expertise in ancient languages and cryptology. Together, they embarked on a quest to unravel the secrets of the symbols and uncover the truth behind the vanishing acts. Days turned into nights as Olivia and Dr. Wolfe immersed themselves in a world of ancient manuscripts and forgotten languages. They unraveled the meanings behind the symbols, leading them to a centuries-old legend—a tale of a malevolent entity known as the Soul Thief, who preyed upon the city's inhabitants, stealing their very essence.",
    "As Olivia dug deeper, she discovered that the Soul Thief's victims were not random. They possessed a unique spiritual energy, an aura that made them vulnerable to the entity's clutches. It became clear that the disappearances were not mere abductions but a sinister plot to empower the Soul Thief and unleash chaos upon the city. Armed with this newfound knowledge, Olivia and Dr. Wolfe raced against time to decipher the Soul Thief's true identity and uncover the key to stopping its reign of terror. They analyzed historical records, studied ancient rituals, and sought out the wisdom of wise elders. Their investigation led them to a hidden underground sect, known as the Guardians of Light, who had sworn to protect the city from the Soul Thief's menace. The Guardians revealed a prophecy that foretold the arrival of a chosen one—a person with a unique connection to the spiritual realm, capable of confronting the Soul Thief and restoring balance. Olivia realized that she was the chosen one, destined to confront the Soul Thief and save her city. She embraced her role, harnessing her inner strength and the wisdom bestowed upon her by the Guardians. The final battle was imminent, and the fate of the city hung in the balance. In a climactic showdown, Olivia faced the Soul Thief, a dark entity draped in shadows and despair. A battle of wills ensued, as Olivia drew upon her inner light and the knowledge she had acquired. With each strike, she weakened the Soul Thief, shattering its hold on the stolen souls.",
    "In the heart of a desolate countryside, nestled among towering trees and overgrown foliage, lay an abandoned mansion known as Ashcroft Manor. Locals whispered chilling tales of the horrors that had befallen its former occupants, warning others to stay away from the cursed estate. But curiosity often has a way of tempting the foolhardy, and one group of thrill-seekers decided to explore the dark secrets that lay within. Amy, Mark, Sarah, and Chris were a group of friends fascinated by the macabre. They reveled in tales of the supernatural, and the legends surrounding Ashcroft Manor seemed too enticing to resist. One moonlit night, armed with flashlights and trembling excitement, they approached the decaying mansion. As they stepped over the threshold, a sense of foreboding washed over them. The air felt heavy, suffocating, as if the mansion itself were inhaling their fear. Dust-covered furniture loomed in the dim light, casting eerie shadows on the peeling wallpaper. Amy's flashlight illuminated a grand staircase leading to the upper floors—a staircase stained with the remnants of an unspeakable tragedy. The group hesitated, exchanging uneasy glances, but their curiosity urged them forward. With each creaking step, the oppressive atmosphere intensified. The walls seemed to whisper ancient secrets, and the temperature dropped as they ascended to the upper levels. It was there, in the heart of the mansion, that they discovered a locked door.",
    "Sarah's fingers trembled as she reached for the tarnished doorknob, her heart pounding in her chest. With a creak, the door swung open, revealing a hidden chamber. The room was adorned with eerie artifacts—masks crafted from human bone, a dusty Ouija board, and faded photographs of long-forgotten faces. As they cautiously explored the room, a sudden gust of wind extinguished their flashlights, plunging them into darkness. Panic swept over the group, as they fumbled in the blackness, searching for an exit. Then, from the shadows, they heard a low, guttural growl—a sound that chilled them to the core. Whispers filled the room, disembodied voices murmuring unintelligible words. Terror took hold of their hearts as unseen hands brushed against their skin, icy tendrils of malevolence. Amy screamed, breaking the oppressive silence, and suddenly, the room was awash with a ghastly light. In its ethereal glow, they saw the tortured figures of ghostly apparitions—faces twisted in anguish, eyes hollow and empty.",
    "Desperation propelled the group forward, as they stumbled through the darkness, blindly searching for an escape. But the mansion seemed to taunt them, its walls shifting and trapping them within its sinister embrace. Hours turned into an eternity as they fought against the mansion's grip, their sanity slipping with each passing moment. Their voices echoed through the hallways, pleading for release from the nightmarish labyrinth.Just as hope waned, a ray of moonlight pierced through a crack in the wall—a glimmer of salvation. With renewed vigor, they followed the light, crawling through narrow passageways and ducking beneath crumbling beams. Finally, they burst through the dilapidated front door, gasping for air as they collapsed onto the overgrown lawn. The mansion loomed behind them, silent and foreboding, as if it were mocking their escape. Days turned into weeks, and the group struggled to piece their lives back together. The horrors of Ashcroft Manor had scarred them, leaving behind a lingering terror that haunted their dreams. They vowed to warn others, to share their harrowing experience as a cautionary tale. Ashcroft Manor remained a dark chapter in their lives—a reminder that some places should remain untouched, their secrets buried in the depths of darkness.",
    "Deep in the heart of a dense forest, an ancient cemetery lay hidden among the towering trees. It was a place of forgotten souls, their names etched on crumbling tombstones that stood as silent sentinels in the moonlit night. Few dared to venture into this forsaken realm, but one group of thrill-seekers sought to test their bravery and unlock the mysteries that lay within. Natalie, James, Emma, and Alex were drawn to the supernatural, their curiosity pushing them to explore the depths of the unknown. Armed with cameras and a sense of trepidation, they entered the cemetery, the air heavy with an otherworldly presence. As they wandered through the overgrown pathways, Natalie's camera captured glimpses of ethereal mist, dancing among the gravestones. James's voice recorder picked up whispers, faint and indecipherable. It seemed as if the very essence of the cemetery was trying to communicate, drawing them deeper into its haunting embrace. Their excitement turned to unease as they stumbled upon an old mausoleum, its iron gates rusted and creaking in the wind. The group hesitated, their eyes meeting in silent contemplation. But the allure of the unknown pushed them forward, and with a collective breath, they entered the crypt. Inside, the air was stale and musty, the sound of their footsteps echoing through the chamber. A sense of foreboding settled upon them, as if unseen eyes watched their every move. The flickering light from their flashlights revealed intricate carvings on the stone walls, depicting scenes of death and despair.",
    "Emma's voice trembled as she suggested conducting a séance to communicate with the spirits that resided within. A mixture of excitement and fear coursed through their veins as they formed a circle and placed their hands upon an ancient Ouija board. They summoned the spirits, their hearts pounding, and asked questions into the abyss. Slowly, the planchette began to move, gliding over the board, spelling out chilling messages. The spirits claimed to be lost souls trapped in the cemetery, yearning for release. As the séance continued, the group felt a palpable shift in the atmosphere. Shadows danced along the walls, growing darker and more menacing. A chilling wind swept through the mausoleum, extinguishing their flashlights one by one. Panic engulfed them as they groped through the darkness, their fingers brushing against cold, stone surfaces. A bone-chilling laughter filled the air, echoing through the crypt. It was as if the spirits had been awaked, their anger unleashed upon the living intruders. Desperate to escape, the group stumbled toward the exit, their hearts pounding with terror. But the mausoleum seemed to shift and elongate, its passages morphing into a labyrinth of death. The spirits taunted them, their voices whispering through the darkness, guiding them deeper into the crypt's twisted corridors.",
    "Time lost all meaning as they fought against the suffocating grip of the cemetery's curse. Their fear threatened to consume them, their minds teetering on the edge of madness. But with a flicker of resilience, they summoned the last vestiges of their courage. They united, their voices rising above the chaos, and called upon the spirits to grant them safe passage. With a blinding burst of light, the mausoleum shattered, and the group emerged into the night air, gasping for breath as they collapsed onto the grassy ground. The cemetery loomed behind them, silent and sinister. They had escaped the clutches of the spirits, forever marked by the horrors they had witnessed. They vowed to never speak of that night, to bury the memories in the depths of their souls. As they parted ways, forever bound by their shared ordeal, the group carried with them the weight of that fateful night—a reminder of the delicate line that separates the living from the realm of the dead. The cemetery would forever remain a forbidden realm, its secrets buried among the forgotten souls who called it home.",
    "In a quaint coastal town, nestled between rolling hills and the sparkling sea, a mysterious circus had set up its tents. The townspeople watched with intrigue as performers in vibrant costumes paraded through the streets, enticing the curious with promises of awe-inspiring acts and unimaginable wonders. Amidst the buzz of anticipation, a young girl named Lily stood at the edge of the crowd, her eyes wide with wonder. The circus had cast its enchanting spell on her, beckoning her to step into a world of magic and mystery. With a surge of excitement, she gathered her courage and made her way toward the entrance. Inside, the atmosphere was electric, as the scent of popcorn mingled with the sound of laughter and the flickering glow of colorful lights. Stalls lined the perimeter, each offering tantalizing games and treats. But it was the tent at the center that held the true allure—an ethereal realm of extraordinary performances. Lily found herself drawn to a tent labeled The Hall of Illusions. As she entered, she was greeted by a charismatic magician named Alexander, his eyes twinkling with secrets. He beckoned her forward, inviting her to experience the wonders he had in store. In the dimly lit room, Alexander performed mind-bending tricks, making objects vanish and reappear, defying the laws of nature. The audience gasped and applauded, their disbelief suspended in the air.",
    "Intrigued, Lily approached Alexander after the show, her eyes shining with curiosity. She asked him about the secret behind his mesmerizing illusions. Instead of dismissing her, he smiled warmly and offered her an invitation to delve deeper into the world of magic. Over the following weeks, Alexander became Lily's mentor, sharing his vast knowledge and teaching her the art of illusion. Together, they practiced sleight of hand, misdirection, and the mastery of illusions. Lily's talent flourished under Alexander's guidance, and she began performing alongside him in the circus. As their bond grew stronger, Alexander confided in Lily about a legendary artifact—a mystical amulet rumored to grant unimaginable power to its bearer. Legends spoke of its ability to create illusions so vivid that they became indistinguishable from reality itself. Driven by curiosity, Lily persuaded Alexander to embark on a quest to find the amulet. Their journey took them to ancient ruins and treacherous landscapes, each step bringing them closer to their goal. Along the way, they faced perilous trials and encountered mysterious characters who either helped or hindered their progress. Finally, they reached a hidden chamber deep within an ancient temple. In the center of the room lay the fabled amulet, gleaming with an ethereal light. As Lily reached out to touch it, the room came alive, illusions springing forth from every corner.",
    "But as they basked in their triumph, they realized that the amulet's power was far greater than they had imagined. The illusions they had conjured began to merge with reality, distorting their surroundings and threatening their very existence. With a surge of determination, Lily and Alexander fought to regain control. They used their knowledge of illusion to counteract the chaos, weaving a new tapestry of reality. It was a battle of minds and wills, as they struggled to regain stability and prevent the world from spiraling into chaos. After what seemed like an eternity, the illusions gradually subsided, and the amulet's power receded. Lily and Alexander stood amidst the remnants of their own creation, panting and exhausted but triumphant. They realized the danger that the amulet posed in the wrong hands and made the decision to seal it away, ensuring its power would never be unleashed again. With heavy hearts, they returned it to its resting place, knowing that it belonged in the realm of legend, where it could no longer wreak havoc on the world. As they emerged from the temple, Lily and Alexander were forever changed. They had witnessed the delicate balance between illusion and reality, the power that lies within the human mind to shape perception. They understood that true magic exists not only in the tricks and illusions they had mastered, but in the ability to inspire wonder and create moments of joy and awe.",
    "Once upon a time, in a small village nestled between rolling hills, there lived a young girl named Emily. She had a heart as bright as the summer sun, and her laughter filled the air with joy. But there was one thing that set Emily apart from the other children—she possessed a magical gift. Emily had the ability to bring to life the drawings she created. With a single stroke of her pencil, her imagination would burst from the page, taking form and color. Her drawings danced and twirled, filling her world with wonder. The village was captivated by Emily's talent. The townspeople would gather in the square, eager to see what magical creations she would unveil. Her drawings brought smiles to faces young and old, spreading happiness wherever they went. One day, as Emily sat beneath her favorite oak tree, she sketched a magnificent bird with vibrant feathers. She poured all her love and imagination into the drawing, infusing it with life. With a wave of her hand, the bird soared into the sky, its wings spanning wide. It chirped with delight, a melody of pure joy. News of Emily's latest creation spread like wildfire, reaching the ears of the village mayor, Mr. Higgins. Intrigued by the girl's extraordinary talent, he saw an opportunity to showcase her abilities to the world. He approached Emily and proposed a grand exhibition—a gallery displaying her magical drawings for all to see.",
    "Emily's heart swelled with excitement at the thought of sharing her gift with a wider audience. With the support of her family and friends, she eagerly accepted the mayor's offer, and preparations began for the grand event. The day of the exhibition arrived, and the village hall was transformed into a gallery adorned with Emily's magical drawings. The walls were adorned with an array of creatures—fierce dragons, whimsical fairies, and enchanted landscapes. The air buzzed with anticipation as the villagers crowded into the gallery. As Emily stood before the crowd, her hand trembling with nervous excitement, she gazed upon her drawings, proud of the magical world she had created. She picked up her pencil and sketched a simple smiley face on a blank sheet of paper. With a flick of her wrist, the smiley face jumped to life, leaping off the page and into the air. It floated above the audience, spreading warmth and happiness throughout the room. The villagers gasped in awe and wonder, their faces lighting up with joy. They marveled at the magic that emanated from Emily's drawings, realizing the power of imagination and the beauty it could bring into their lives. As the exhibition continued, people from neighboring villages flocked to witness Emily's extraordinary gift. She inspired artists, young and old, to embrace their creativity and explore the limitless boundaries of their imagination. The gallery became a beacon of hope and wonder, a place where dreams took flight.",
    "In a forgotten corner of the world, a seed sprouted from the fertile earth. It grew, stretching its delicate tendrils toward the sun. Day by day, it reached higher, its leaves unfurling with a vibrant green hue. As the seasons changed, the seedling transformed into a magnificent tree. Its branches reached out like welcoming arms, providing shade and shelter to all who sought refuge beneath its canopy. Birds sang in its branches, and woodland creatures found solace in its embrace. Generations passed, and the tree became a symbol of strength and resilience. It stood tall through storms and winds, its roots anchored deep into the earth. It witnessed the rise and fall of civilizations, silently witnessing the passage of time. People marveled at its grandeur, their hearts touched by its timeless presence. They gathered beneath its branches, sharing stories and laughter. The tree became a gathering place, a sanctuary where bonds were formed, and memories were made. In the twilight of its existence, as its branches weathered with age, the tree knew its time was drawing near. But it was not afraid, for it had fulfilled its purpose, bringing beauty and solace to all who had crossed its path. One peaceful night, as the moon cast a gentle glow upon the land, the tree's leaves whispered their farewell. Its roots released their hold on the earth, and with a graceful sigh, it gracefully toppled to the ground",
    "The Stolen Heirloom In the quiet town of Willowbrook, a notorious art thief named Vincent Dupont had set his sights on the priceless sapphire necklace known as the Willowbrook Heirloom. The necklace had been a cherished possession of the town's prominent Montclair family for generations. Determined to retrieve their family's treasure, the Montclairs hired private investigator, Detective Emily Sullivan.  As Emily delved into the case, she uncovered a web of deceit and secrets. The Montclair family had been feuding for years, and each member held a motive for the theft. Emily interviewed the suspects, carefully navigating through their lies and half-truths. With her keen eye for detail, Emily noticed a pattern. Each suspect had an alibi for the night of the theft, making it seem impossible for any of them to be the culprit. But Emily had a hunch that the truth lay hidden within the Montclair mansion itself. During a clandestine investigation, Emily stumbled upon a hidden chamber beneath the mansion's library. In the secret room, she discovered a collection of stolen artwork and stolen artifacts. The evidence pointed to the Montclair family being involved in an elaborate art smuggling operation. In a tense confrontation, Emily confronted the Montclair family with her findings. They admitted their involvement in the illegal activities, driven by greed and a desire to maintain their lavish lifestyle. However, they denied stealing the Willowbrook Heirloom, claiming they were unaware of its whereabouts. Refusing to back down, Emily continued her investigation. Following a trail of clues, she traced the stolen necklace to an underground criminal organization led by none other than Vincent Dupont. He had been working in secret with a member of the Montclair family to orchestrate the heist. In a dramatic showdown, Emily confronted Dupont and the Montclair family member at an abandoned warehouse. With her quick thinking and sharp instincts, Emily outwitted the criminals, securing the necklace and bringing them to justice. The Willowbrook Heirloom was returned to the Montclair family, and the town of Willowbrook breathed a sigh of relief. Detective Emily Sullivan became a local hero, known for her relentless pursuit of justice. The case served as a reminder that even in the most seemingly idyllic communities, darkness could lurk beneath the surface.",
    "The Vanishing Art In the heart of the bustling city, an enigmatic art thief known as the Phantom had been orchestrating a series of daring heists. The Phantom targeted only the most valuable and elusive pieces of artwork, leaving the police baffled and the art world in a state of panic. Detective Lucas Grant, renowned for his uncanny ability to solve complex cases, was assigned to capture the Phantom and put an end to the crime spree. With his sharp intuition and meticulous approach, Lucas set out to decipher the Phantom's modus operandi. After studying the stolen artworks, Lucas noticed a recurring theme—they were all masterpieces from the same reclusive artist, Victor Renard. Determined to understand the connection, Lucas delved into Renard's mysterious past, unearthing a tragic tale of unrequited love and shattered dreams. As Lucas dug deeper, he discovered that the Phantom was none other than Victor Renard himself. Driven by bitterness and resentment, Renard had vowed to take back what he believed was rightfully his—the recognition and fame he felt he had been denied. Lucas tracked Renard to an abandoned warehouse on the outskirts of the city. In a climactic confrontation, the detective confronted the artist, his heart heavy with sympathy for the broken man before him. He implored Renard to end the cycle of theft and destruction, reminding him that true artistry lies in creation, not in theft.",
    "The Mysterious Break-In In the heart of the city, a high-profile jewelry store known as Diamond Delights was targeted in a daring heist. The store boasted an impressive collection of rare gems and exquisite diamonds, making it an irresistible target for thieves. Detective Mark Reynolds, known for his sharp instincts and dogged determination, was assigned to crack the case. As he examined the crime scene, he noticed peculiar details—a broken lock, a faint footprint, and a single, glittering diamond left behind. With these clues in hand, Mark began his investigation, uncovering a network of underground criminals who specialized in high-value heists. The trail led him to a notorious gang led by the elusive mastermind known as The Phantom. Mark delved into the criminal underworld, gathering intelligence and tracking the gang's activities. Through meticulous surveillance, he identified their hideout—an abandoned warehouse on the outskirts of town. In a dramatic raid, Mark and his team stormed the warehouse, apprehending the gang members. However, The Phantom managed to escape, leaving behind a cryptic message hinting at his next target—the city's prestigious art museum.",
    "The Disappearing Act In a town renowned for its annual magic festival, a renowned magician named Victor Voss was preparing for his grand performance. Victor was known for his jaw-dropping illusions, leaving audiences spellbound with his mastery of sleight of hand. However, just days before the festival, disaster struck—Victor's treasured magical artifact, the Enchanter's Deck, vanished. The deck held immense power, capable of turning dreams into reality in the hands of a skilled magician. Determined to reclaim his prized possession, Victor sought the help of Detective Maya Sullivan, a seasoned investigator with an eye for detail. As they delved into the case, they discovered a rival magician named Damien Drake, known for his jealousy of Victor's success. Maya and Victor suspected Damien of stealing the Enchanter's Deck to sabotage Victor's performance. Their investigation took them through a maze of misdirection and illusion, forcing them to unravel the secrets of the magic world. As they uncovered Damien's motive—a desire to steal the spotlight and establish his dominance—the duo raced against time to expose him. They analyzed past performances, studied illusions, and scrutinized every move Damien made. In a thrilling climax, Victor took to the stage for his performance, while Maya and her team kept a close eye on Damien. As Victor performed his finale, a stunning illusion that mesmerized the crowd, Maya caught Damien red-handed attempting to steal another magician's artifact.",
    "The Cold Case Revived In a small town plagued by unsolved mysteries, a cold case resurfaced, sending shockwaves through the community. The case involved the disappearance of Sarah Thompson, a young woman who had vanished without a trace five years ago. Detective Ethan Harris, known for his relentless pursuit of justice, took on the long-forgotten case. As he revisited the evidence and interviewed witnesses, he realized that there were loose ends and overlooked leads that could shed light on Sarah's disappearance. With renewed determination, Ethan retraced Sarah's last known steps. He combed through old police records, re-interviewed witnesses, and uncovered a crucial piece of evidence—a forgotten surveillance tape from the night Sarah vanished. Analyzing the grainy footage, Ethan discovered a figure lurking in the shadows, someone who had never been identified or questioned. The breakthrough led him to a reclusive artist named James Monroe, known for his eerie paintings that mirrored Sarah's disappearance. As Ethan investigated further, he discovered that James had an obsession with capturing the essence of tragedy and mystery in his artwork. The detective realized that James might hold the key to Sarah's fate. In a tense confrontation, Ethan confronted James, presenting him with the evidence and demanding the truth. James, tormented by guilt, confessed to kidnapping and accidentally causing Sarah's death, hiding her body within one of his chilling paintings.",
    "The Art of Deception In the prestigious art world, a series of high-profile forgeries had been circulating, leaving experts and collectors puzzled. The fakes were so convincing that they fooled even the most discerning eyes, threatening to undermine the integrity of the art market. Enter Gabriel Hunter, a renowned art historian and detective known for his expertise in art authentication. Gabriel was determined to uncover the mastermind behind the forgeries and restore integrity to the art world. As Gabriel delved into the case, he discovered a trail of suspicious transactions and connections. The evidence led him to a notorious art dealer named Lucien Dubois, known for his shady dealings and unscrupulous practices. Gabriel's investigation took him on a thrilling journey through hidden auction houses, shadowy art galleries, and exclusive private collections. He enlisted the help of an art expert and a computer hacker to gather the evidence needed to expose the forgery ring. In a dramatic confrontation, Gabriel confronted Lucien and his associates at an extravagant art auction. With a stunning reveal, Gabriel exposed the forgeries, unveiling the true extent of Lucien's deception.",
    "The Case of the Vanishing Diamond In the heart of a bustling city, a rare and valuable diamond known as the Star of Aranya was put on display at the grand opening of the city's newest museum. The diamond's arrival had caused a stir among collectors and enthusiasts from around the world. However, just hours before the unveiling, disaster struck—the diamond vanished from its heavily guarded case. The museum was thrown into chaos, and the local police department was called in to solve the baffling crime. Detective Rachel Collins, known for her sharp intellect and unwavering determination, took charge of the investigation. She carefully analyzed the crime scene, studying surveillance footage and interviewing museum staff and attendees. As Rachel delved deeper into the case, she discovered a complex web of intrigue and deceit. A prominent art collector, a skilled jewel thief, and a museum employee with a troubled past emerged as the primary suspects. With each twist and turn, Rachel gathered evidence and followed leads, untangling the intricate threads of the case. Her intuition led her to a secret underground network of black-market art dealers known as The Shadow Syndicate."
];
const typingText = document.querySelector(".typing-text p"),
inpField = document.querySelector(".wrapper .input-field"),
timeTag = document.querySelector(".content .time span b"),
mistakeTag = document.querySelector(".content .mistakes span");
wpmTag = document.querySelector(".content .wpm span");
cpmTag = document.querySelector(".content .cpm span");
tryAgainBtn = document.querySelector("button");
 
let timer,
maxTime = 60,
timeLeft = maxTime;

let mistakes = characterIndex = isTyping = 0;

function randomParagraph(){
    let randIndex = Math.floor(Math.random() * paragraphs.length);
    typingText.innerHTML = '';
    paragraphs[randIndex].split("").forEach(span => {
        let spanTag = `<span>${span}</span>`;
        typingText.innerHTML += spanTag;
    });
    typingText.querySelectorAll("span")[0].classList.add("active");
    document.addEventListener("keydown", () => inpField.focus());
    typingText.addEventListener("click", () => inpField.focus());

}

function initTyping(){
    const characters = typingText.querySelectorAll("span");
    let typedChar = inpField.value.split("")[characterIndex];

    if (characterIndex < characters.length -1 && timeLeft > 0){
        if (!isTyping){
        timer = setInterval(initTimer,1000);
        isTyping = 1;
        }
        if (typedChar == null){
            characterIndex--;
            if(characters[characterIndex].classList.contains("incorrect")){
                mistakes--;}
            
            characters[characterIndex].classList.remove("correct","incorrect");
        }
        else{ if(characters[characterIndex].innerText === typedChar){
            characters[characterIndex].classList.add("correct");
        }
        else{
            mistakes++;
            characters[characterIndex].classList.add("incorrect");
        }
        
       characterIndex++;
    }
    characters.forEach(span => span.classList.remove("active"));
    characters[characterIndex].classList.add("active");
    
    
    wpm = Math.round((((characterIndex - mistakes) / 5) / (maxTime-timeLeft)) * 60);
    wpm = wpm < 0 || wpm === Infinity || !wpm ? 0 : wpm;
    
    wpmTag.innerHTML = wpm;
    mistakeTag.innerHTML = mistakes;
    cpmTag.innerHTML = characterIndex - mistakes;
    }
    else{
        inpField.value = "";
        clearInterval(timer);
    }
    
}

function initTimer() {
    if (timeLeft > 0){
        timeLeft--;
        timeTag.innerHTML = timeLeft;
    }
    else{
        clearInterval(timer);
    }

}

randomParagraph();

function resetGame(){
    randomParagraph();
    timeLeft = maxTime;
    let mistakes = characterIndex = isTyping = 0;
    timeTag.innerHTML = timeLeft;
    wpmTag.innerHTML = 0;
    mistakeTag.innerHTML = mistakes;
    cpmTag.innerHTML = 0;
    inpField.value = "";
    clearInterval(timer);
}

inpField.addEventListener("input",initTyping);
tryAgainBtn.addEventListener("click",resetGame)